FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["TuitionHub.Api/TuitionHub.Api.csproj", "TuitionHub.Api/"]
COPY ["TuitionHub.Application/TuitionHub.Application.csproj", "TuitionHub.Application/"]
COPY ["TuitionHub.Domain/TuitionHub.Domain.csproj", "TuitionHub.Domain/"]
COPY ["TuitionHub.Infrastructure/TuitionHub.Infrastructure.csproj", "TuitionHub.Infrastructure/"]
RUN dotnet restore "TuitionHub.Api/TuitionHub.Api.csproj"
COPY . .
RUN dotnet publish "TuitionHub.Api/TuitionHub.Api.csproj" -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
EXPOSE 8080
COPY --from=build /app .
ENTRYPOINT ["dotnet", "TuitionHub.Api.dll"]
